DEFAULT_EMBEDDING_MODEL_ID = "sentence-transformers/multi-qa-MiniLM-L6-cos-v1"
DEFAULT_GEMINI_MODEL_ID = "gemini-2.5-flash-lite"

DEFAULT_TOKENIZER_MODEL_ID = "bert-base-uncased"
DEFAULT_MAX_TOKENS_PER_CHUNK = 256
DEFAULT_MAX_CHUNK_OVERLAP = 32
